version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/server
    overwrite: true
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ec2-user/server
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 600
      runas: ec2-user